### ISSUE TITLE
It was slower than Java

### ISSUE THREAD

**Issue by SudoDios** [Zunawe/md5-c#3]
Hi developer.
I tested with a 3.2Gb file and Java was 7 seconds faster than this.
Can't you increase the speed 😅 ?

**Comment by SudoDios** [comment]
Is there anything that can calculate in less than 1 second?

**Comment by Zunawe** [comment]
The purpose of this repo is to be a clear and readable reference implementation, not to run quickly. You're welcome to fork it, but I don't intend on optimizing this code.

**Comment by SudoDios** [comment]
OK
Sorry.
I was looking for something quick

**Comment by fetisov** [comment]
The code looks good from a performance standpoint. At least with the -O3 compiler option, there should be no significant performance loss. I advise you to check whether your Java implementation uses hardware acceleration.
