### ISSUE TITLE
`md5String` / `md5File` - `malloc` without `free`ing

### ISSUE THREAD

**Issue by demberto** [Zunawe/md5-c#4]
### Problem
`md5String` / `md5File` `malloc` 16 bytes for the returned result and return that malloc'd pointer. It doesn't document this behaviour. A user will have to manually `free` that block of memory. This can be a big problem, if for example the code in this library is used between two programs using different implementations of `malloc` & `free`.

### Solution
A more cleaner and idiomatic way would be to fill a caller passed 16-byte buffer with the result.
```c
void md5String(char* string, uint8_t* result);
```
This way the caller would manage the memory used by your function and be able to use the stack (instead of malloc).

**Comment by Zunawe** [comment]
This is pretty reasonable and easy to change. Does that commit work?
